In [ ]:
import pandas as pd
from pathlib import Path
import sys
sys.path.append(str(Path().resolve().parent))
from data_preprocessing.preprocessing import preprocessing
from eda_ftr_eng.EDA import eda

df_raw = pd.read_csv('../Data/Raw/Job_Frauds.csv', encoding='latin-1')
preprocessed_df = preprocessing(df_raw)
#then rebalancing - tbc
df = eda(preprocessed_df)


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\eilee\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ipykernel_l

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\eilee\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ipykernel_l

AttributeError: _ARRAY_API not found

C:\Users\eilee\OneDrive - National University of Singapore\DSA4263\DSA4263-Project\data_preprocessing\preprocessing.py:27: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.lower() if isinstance(x, str) else x)


## Feature Engineering: Converting text features to vectors for modelling

In [ ]:
#CAN GROUP THESE TOGETHER FOR ONE HOT
len(df['Qualification'].unique())
df['Qualification'].unique()

array([nan, 'bachelors degree', 'masters degree',
       'high school or equivalent', 'unspecified',
       'some college coursework completed', 'vocational', 'certification',
       'associate degree', 'professional', 'doctorate',
       'some high school coursework', 'vocational  degree',
       'vocational  hs diploma'], dtype=object)

In [ ]:
def simplify_qualification(q):
    if pd.isna(q) or q == "unspecified":
        return "Unspecified"
    elif q in ["high school or equivalent", "some high school coursework", "vocational hs diploma"]:
        return "High School"
    elif q in ["vocational", "vocational degree", "certification", "professional"]:
        return "Vocational / Certification/ Professional"
    elif q == "some college coursework completed":
        return "Some College"
    elif q == "associate degree":
        return "Associate Degree"
    elif q == "bachelors degree":
        return "Bachelor's Degree"
    elif q == "masters degree":
        return "Master's Degree"
    elif q == "doctorate":
        return "Doctorate"
    else:
        return "Other"

df['Qualification'] = df['Qualification'].apply(simplify_qualification)

# One-Hot Encode
# df = pd.get_dummies(df, columns=['Qualification_Simplified'], drop_first=True)


In [ ]:
# Combined back the words to form sentence for vector embedding
text_columns = ['Profile', 'Job_Description', 'Requirements', 'Job_Benefits']
for col in text_columns:
    # df[col] = df[col].apply(lambda x: ' '.join(x) if isinstance(x, list) else str(x))
    df[col] = df[col].str.replace(r'[\[\]\'\",]', '', regex=True)


In [ ]:
df.head(5)

Job Title Department Range_of_Salary  \
0                          marketing intern  marketing             NaN   
1  customer service  cloud video production    success             NaN   
2     commissioning machinery assistant cma        NaN             NaN   
3          account executive  washington dc      sales             NaN   
4                       bill review manager        NaN             NaN   

                                             Profile  \
0  food52 weve created groundbreaking awardwinnin...   
1  90 second world cloud video production service...   
2  valor service provides workforce solution meet...   
3  passion improving quality life geography heart...   
4  spotsource solution llc global human capital m...   

                                     Job_Description  \
0  food52 fastgrowing james beard awardwinning on...   
1  organised focused vibrant awesomedo passion cu...   
2  client located houston actively seeking experi...   
3  company esri â environmental system research i...   
4  job title itemization review managerlocation f...   

                                        Requirements  \
0  experience content management system major plu...   
1  expect youyour key responsibility communicate ...   
2  implement precommissioning commissioning proce...   
3  educationâ bachelorâs masterâs gi business adm...   
4  qualificationsrn license state texasdiploma ba...   

                                        Job_Benefits  Telecomunication  \
0                                                nan                 0   
1  get usthrough part 90 second team gainexperien...                 0   
2                                                nan                 0   
3  culture anything corporateâwe collaborative cr...                 0   
4                               full benefit offered                 0   

   Comnpany_Logo Type_of_Employment       Experience      Qualification  \
0              1              other       internship        Unspecified   
1              1           fulltime   not applicable        Unspecified   
2              1                NaN              NaN        Unspecified   
3              1           fulltime  midsenior level  Bachelor's Degree   
4              1           fulltime  midsenior level  Bachelor's Degree   

            Type_of_Industry            Operations  Fraudulent Country State  \
0                        NaN             marketing           0      us    ny   
1  marketing and advertising      customer service           0      nz   NaN   
2                        NaN                   NaN           0      us    ia   
3          computer software                 sales           0      us    dc   
4      hospital  health care  health care provider           0      us    fl   

         City  
0    new york  
1    auckland  
2       wever  
3  washington  
4  fort worth

## Checking Country City State, seems sus, maybe just use Country only?

In [ ]:
len(df['Country'].unique())
df['Country'].unique()

array(['us', 'nz', 'de', 'gb', 'au', 'sg', 'il', 'ae', 'ca', 'in', 'eg',
       'pl', 'gr', 'pk', 'be', 'br', 'sa', 'dk', 'ru', 'za', 'cy', 'hk',
       'tr', 'ie', 'lt', 'jp', 'nl', 'at', 'kr', 'fr', 'ee', 'th', 'pa',
       'ke', 'mu', 'mx', 'ro', 'my', 'fi', 'cn', 'es', 'se', 'cl', 'ua',
       'qa', 'it', 'lv', 'iq', 'bg', 'ph', 'cz', 'vi', 'mt', 'hu', 'bd',
       'kw', 'lu', 'ng', 'rs', 'by', 'vn', 'id', 'zm', 'no', 'bh', 'ug',
       'ch', 'tt', 'sd', 'sk', 'ar', 'tw', 'pt', 'pe', 'co', 'is', 'si',
       'ma', 'am', 'tn', 'gh', 'al', 'hr', 'cm', 'sv', 'ni', 'lk', 'jm',
       'kz', 'kh'], dtype=object)

In [ ]:
import pandas as pd
from scipy.stats import chi2_contingency

def categorical_correlation(column):
    contingency_table = pd.crosstab(df[column], df['Fraudulent'])
    chi2, p, _, _ = chi2_contingency(contingency_table)
    cramers_v = np.sqrt(chi2 / (len(df) * (min(contingency_table.shape) - 1)))
    return cramers_v

print("Country correlation:", categorical_correlation('Country'))
print("State correlation:", categorical_correlation('State')) 
print("City correlation:", categorical_correlation('City'))

Country correlation: 0.19292954038212332
State correlation: 0.25321538911856023
City correlation: 0.5747512976643746


In [ ]:
# Compare models with different geographic granularity
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

X_country = pd.get_dummies(df['Country'])
X_state = pd.get_dummies(df[['Country', 'State']].fillna('').astype(str).apply('_'.join, axis=1))
X_city = pd.get_dummies(df[['Country', 'State', 'City']].fillna('').astype(str).apply('_'.join, axis=1))

print("Country only CV score:", cross_val_score(RandomForestClassifier(), X_country, df['Fraudulent']).mean())
print("Country+State CV score:", cross_val_score(RandomForestClassifier(), X_state, df['Fraudulent']).mean()) 
print("Full geo CV score:", cross_val_score(RandomForestClassifier(), X_city, df['Fraudulent']).mean())

Country only CV score: 0.9517480237959415
Country+State CV score: 0.951633966196854
Full geo CV score: 0.9509491000884711


## Encodoing

In [ ]:
from sentence_transformers import SentenceTransformer

columns_for_embedding = ['Job Title', 'Profile', 'Department', 'Job_Description', 'Requirements', 'Job_Benefits', 'Type_of_Industry', 'Operations',]
categorical_columns = ['Type_of_Employment','Experience', 'Qualification', 'Country']

model = SentenceTransformer('all-MiniLM-L6-v2')
for col in columns_for_embedding:
    print(f"Embedding column: {col}")
    df[f"{col}_embed"] = model.encode(df[col].fillna(""))

Embedding column: Job Title
Embedding column: Profile
Embedding column: Department
Embedding column: Job_Description
Embedding column: Requirements
Embedding column: Job_Benefits
Embedding column: Type_of_Industry
Embedding column: Operations


In [ ]:
df['Profile'].unique()

array([nan, 'Unspecified'], dtype=object)

In [ ]:
new_df

Job Title  Department Range_of_Salary   Profile  Job_Description  \
0      -0.045861   -0.054776     Unspecified -0.118838        -0.118838   
1      -0.024208   -0.008672     Unspecified -0.118838        -0.118838   
2      -0.117126   -0.010108     Unspecified -0.118838        -0.118838   
3       0.004597   -0.069585     Unspecified -0.118838        -0.118838   
4      -0.077730   -0.010108     Unspecified -0.118838        -0.118838   
...          ...         ...             ...       ...              ...   
17528   0.035726   -0.069585     Unspecified -0.118838        -0.118838   
17529  -0.075184   -0.024759     Unspecified -0.118838        -0.118838   
17530  -0.069088   -0.010108     Unspecified -0.118838        -0.118838   
17531  -0.055324   -0.010108     Unspecified -0.010108        -0.118838   
17532  -0.054188   -0.070995     Unspecified -0.118838        -0.118838   

       Requirements  Job_Benefits  Telecomunication  Comnpany_Logo  \
0         -0.118838     -0.010108                 0              1   
1         -0.118838     -0.118838                 0              1   
2         -0.118838     -0.010108                 0              1   
3         -0.118838     -0.118838                 0              1   
4         -0.118838     -0.118838                 0              1   
...             ...           ...               ...            ...   
17528     -0.118838     -0.118838                 0              1   
17529     -0.118838     -0.118838                 0              1   
17530     -0.118838     -0.010108                 0              0   
17531     -0.118838     -0.118838                 0              0   
17532     -0.118838     -0.010108                 0              1   

      Type_of_Employment       Experience  \
0                  other       internship   
1               fulltime   not applicable   
2            Unspecified      Unspecified   
3               fulltime  midsenior level   
4               fulltime  midsenior level   
...                  ...              ...   
17528           fulltime  midsenior level   
17529           fulltime  midsenior level   
17530           fulltime      Unspecified   
17531           contract   not applicable   
17532           fulltime  midsenior level   

                                  Qualification  Type_of_Industry  Operations  \
0                                         Other         -0.010108   -0.054776   
1                                         Other         -0.033716   -0.149438   
2                                         Other         -0.010108   -0.010108   
3                             Bachelor's Degree         -0.076391   -0.069585   
4                             Bachelor's Degree         -0.024020   -0.089137   
...                                         ...               ...         ...   
17528                                     Other         -0.076391   -0.069585   
17529                         Bachelor's Degree         -0.015799    0.006420   
17530                                     Other         -0.010108   -0.010108   
17531  Vocational / Certification/ Professional         -0.003971   -0.052529   
17532                                     Other         -0.076391   -0.070995   

       Fraudulent Country        State          City  
0               0      us           ny      new york  
1               0      nz  Unspecified      auckland  
2               0      us           ia         wever  
3               0      us           dc    washington  
4               0      us           fl    fort worth  
...           ...     ...          ...           ...  
17528           0      ca           on       toronto  
17529           0      us           pa  philadelphia  
17530           0      us           tx       houston  
17531           0      ng           la         lagos  
17532           0      nz            n    wellington  

[17533 rows x 18 columns]

In [ ]:
new_df['Profile'].unique()

array([-0.11883842, -0.01010849, -0.11883846, -0.11883839], dtype=float32)

In [ ]:
# Verify the embedding shape
print(new_df['Job Title'].iloc[0].shape)  # Should output (384,)
print(type(new_df['Job Title'].iloc[0]))   # Should output <class 'numpy.ndarray'>

()
<class 'numpy.float32'>
